# Generated by Django 5.1.2 on 2025-06-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('expenses', 'Expenses'), ('icome', 'Income')], max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
